spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update